### ISSUE TITLE
editing logbook entry with images does not work

### ISSUE THREAD

**Issue by epanepucci** [paulscherrerinstitute/scilog#129]
When I tried editing an entry in the logbook (3-dot menu) it brings up an editing dialog but when I submit the entry it is duplicated & broken

**Comment by stephan271** [comment]
We can not reproduce the error currently. Can you give us an example logbook entry which caused this problem ?

Also: after reloading the browser window is the entry appearing as expected ?

**Comment by minottic** [comment]
images are no longer found even before submitting the edition
