### ISSUE TITLE
should warn user if changing the layout with uncommited content

### ISSUE THREAD

**Issue by epanepucci** [paulscherrerinstitute/scilog#131]
Currently, if I type content and click to go to another widget I'll loose all of it.

option 1)
the app should warn the user if it tries to leave the page with content that hasn't been sent/commited.

option 2)
the app should remember the uncommited content for the current user

**Comment by stephan271** [comment]
Agreed, contents should be kept !
One question: when exactly does this happen for you: when clicking on another widget in the current view or when using the navigation buttons to the left to switch between individual widget display vs full view display ?

**Comment by epanepucci** [comment]
it happens when either navigating to a different widget then going back or if I click the maximize widget button. so whenever the layout changes I think.
