### ISSUE TITLE
Reply on comments is not working as expected

### ISSUE THREAD

**Issue by PhilippJo** [paulscherrerinstitute/scilog#177]
Replying on a usual paragraph adds a new snippet at the end, while replying to a comment adds the reply not at the end, but instead, to the comment and the original position of the comment snippet.

**Comment by stephan271** [comment]
Thats is the intended behaviour. What would you expect instead ?

**Comment by PhilippJo** [comment]
Ah ok, if its intended thats fine, I would have expected that both, paragraph snippet and comment snippet, trigger the same behavior if a reply is added. So to say, that in both cases the reply is posted right at the end of the logbook, as a new snippet, and in that way get the most attention from the users. But jeah it makes sense to add a reply to a comment right were the comment is and not to overcrowd the feed, but then the reply may be overseen.
