### ISSUE TITLE
Problem with cancelling reply

### ISSUE THREAD

**Issue by PhilippJo** [paulscherrerinstitute/scilog#181]
When pressing cancel or add in the reply window for a specific snippet, the time and email is vanished from the metadata heading of the snippet and its no longer possible to add another comment or reply(add button is gone). Reloading the page resolves the issue. 
tested on Firefox 109.0.1 and Chrome 109.0.5414.120
![expReply](https://user-images.githubusercontent.com/94835020/216991492-e92a3d7e-7dad-4408-9af9-94212ae75eb8.PNG)

**Comment by stephan271** [comment]
We can confirm the bug
