### ISSUE TITLE
Simplify Login page for the user

### ISSUE THREAD

**Issue by stephan271** [paulscherrerinstitute/scilog#25]
The user should just see one button "Login with PSI account" when going to the scilog startpage. When pressing the button she is immediately sent to the IDP login page (no intermediate keycloak step) at first time. For subsequent logins this step will be skipped because the login info is cached.

To allow to login with functional accounts the two login fields for the functional accounts only appear after pressing a link "Expert access" somewhere below the "Login with PSI account" button. Entering functional account username and password will lead the expert user directly into scilog.

In the future the keycloak step may need to be re-activated, e.g. when another IDP like Umbrella accounts would be added

**Comment by minottic** [comment]
@stephan271 this can be closed right?
