### ISSUE TITLE
linebreaks are not displaying correctly

### ISSUE THREAD

**Issue by N-Phillips** [paulscherrerinstitute/scilog#260]
Return/enter linebreaks in entries are not displaying correctly. They appear as a tab space, rather than linebreak. See image:

![image](https://github.com/paulscherrerinstitute/scilog/assets/127228076/8afab387-9c1d-4361-a02f-0e84d893f127)

**Comment by simondelabici** [comment]
BVB. , xxx

**Comment by N-Phillips** [comment]
Hi @minottic 

Thanks for looking into this. I can confirm that the issue appears fixed in a Chrome browser. However, from Firefox the newline displaying is still not working correctly. - It is the same as before. 

From linux PC's at the beamline we must use firefox, or at least not Chrome (don't get me started on why...). It would be very helpful if you could please continue to look into this issue.

**Comment by wakonig** [comment]
Hi @N-Phillips 
Could you try and delete the cache in firefox? Sometimes the old version is cached there. Thanks!

**Comment by N-Phillips** [comment]
@wakonig @minottic 

Thanks clearing the cache fixed it. Sorry!!!

**Comment by wakonig** [comment]
No problem at all! Good that it works now :)
