### ISSUE TITLE
Export pdf: export of table produces layout problem

### ISSUE THREAD

**Issue by PhilippJo** [paulscherrerinstitute/scilog#329]
## Issue Name
Export pdf: export of table produces layout problem
### Summary
The export of a logbook including tables results in a changed formatting and loss of information. 
### Steps to Reproduce
1) Create logbook and enter some text and table snippets 
2) Export to pdf
### Current Behaviour
If a table is included in the logbook, the respective page of the pdf is roated from portrait to landscape format, the text snippets on the same page are cut (-> information is lost) and the table is always shown on the top of a new page
### Expected Behaviour
The table is included in place, if there is enough space to include the whole table, the format is not rotated, all informations are perserved and a continious style is achived. 
### Extra Details
![image](https://github.com/paulscherrerinstitute/scilog/assets/94835020/433fe3f5-2758-4688-b5f4-7fd28e287b79)

Here you should include details about the system (if it is unique) and possible information about a fix (feel free to link to code where relevant). Screenshots/GIFs are also fine here.

**Comment by minottic** [comment]
could you please include a screenshot of the logbook, before the export?

**Comment by PhilippJo** [comment]
Here is a screenshot of the actual logbook
![grafik](https://github.com/paulscherrerinstitute/scilog/assets/94835020/096ca92c-3ecd-44c6-8059-600ce5f27fc0)

**Comment by minottic** [comment]
what browser/PDF reader do you use?

**Comment by PhilippJo** [comment]
I checked it with 
Firefox 122.0
Chrome 121
PDF-XChange Viewer 2.5
Adobe Acrobat Reader 23.008

**Comment by minottic** [comment]
do you still have access to the scilog.development.psi.ch?

**Comment by PhilippJo** [comment]
yes I do

**Comment by minottic** [comment]
ok, if you login there you should see a logbook named: `pdf download` could you please add the content there and try to download? I will try that myself and see if we get the same result. I get aswell the table in landscape (which is the expected behaviour), but I don't see the content being cut

**Comment by PhilippJo** [comment]
still get the same content loss. 
![grafik](https://github.com/paulscherrerinstitute/scilog/assets/94835020/665e64b3-7a81-4571-b4de-8fb282c63be0)

**Comment by minottic** [comment]
ok, thanks, I could replicate now. It gets fixed if you add a new line after the table. I will have a look at a proper fix
