### ISSUE TITLE
Ensure image sizes are correct at initial HTML rendering

### ISSUE THREAD

**Issue by stephan271** [paulscherrerinstitute/scilog#43]
The size needed for images should be determined at initial rendering time to avoid any jumps in the HTML renderer.

**Comment by wakonig** [comment]
I cannot reproduce the jump we've seen on Friday. Could it be that it is related to the failed image rendering (due to the wrong e2sci import)?

**Comment by stephan271** [comment]
Yes, that could be . I will close ths issue for now until the effect reappears (hopefully not ;-) )
